name: Protoc Runner

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Run Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.6"
      - name: Run Protoc
        run: protoc order.proto --java_out=.
      - name: List Files
        run: ls -R
      - name: Print file
        run: cat docs/javadsl/proto/OrderMessages.java
